"""add admin column

Revision ID: 85635f493859
Revises: 138ef11935d5
Create Date: 2020-12-06 13:42:14.722319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85635f493859'
down_revision = '138ef11935d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
